### ISSUE TITLE
Mbrola 253 error

### ISSUE THREAD

**Issue by monhi** [tihu-nlp/tihu#31]
Hi, 
I installed all tihu packages based on MD file and installation was successful.
But when I run sample code, I get "mbrolla exited with status 253"

Please let me know how to resolve it 

Thanks

**Comment by b00f** [comment]
Hi. Thanks for using Tihu. I think this issue is related to bad mbrola installation. Please download mbrola at [here](https://github.com/numediart/MBROLA) and compile it manually. Make sure mbrola has execute permission.

**Comment by monhi** [comment]
Hi Mostafa, 
Thanks for you comment, It works perfect now.
But now I would like to add vowels like fathe and kasre and zame to some words to connect them to each other. please help me to use it in ubuntu linux
من قصد دارم که با استفاده از فتحه و کسره و ضمه برخی حروف را به هم مرتبط کنم. الان صدا بسیار ماشینی است و در صورت رفع این مشکل صدا کیفیت بهتری خواهد داشت. 
لطفا بفرمایید که به چه ترتیب این کار را انجام دهم.
با تشکر فراوان

**Comment by b00f** [comment]
Please look at #27 and #28 and #29.  
About the voice quality, Still we can improve the quality of the voice by some modification in the code. However we can think about producing better Speech synthesizer for Persian language probably using [festvox](http://festvox.org/)
