### ISSUE TITLE
I need Help :(

### ISSUE THREAD

**Issue by theamircodex** [tihu-nlp/tihu#49]
Hello first of all thanks for this amazing project
and the question is, how can I import and use Persian text to speech in python project ??

**Comment by b00f** [comment]
You may add Python support and send a PR

**Comment by theamircodex** [comment]
I know but I mean how to import tihu into python project
something like this

> pip install tihu
> import tihu as thp

and use it in python project 
could u explain what should I do ? please

**Comment by b00f** [comment]
Unfortunately I am not familiar with this. @ebraminio do you have any idea?

**Comment by ebraminio** [comment]
یکم پیچیده هست مراحل نصب و استفاده‌ش امیر جان و به صورت کتابخونهٔ پایتونی ارائه نمی‌شه متأسفانه :/ شرمنده
