### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by theamircodex** [tihu-nlp/tihu#51]
Hello thanks for this amazing project .
and I was visiting the demo of that in lilak-project.com
and it wasn't working and I got this error 504 Gateway Time-out please fix that 
thank u <3

**Comment by b00f** [comment]
Since it is using Python 2 and python 2 is deprecated, there is difficulty to support it right now. This is why I removed it from the website. 
I don't have time to fix it right now. Sorry
