### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [tihu-nlp/tihu#8]
https://github.com/tihu-nlp/tihu/blob/8c61e1cd155e55301f09b65d6ad33ea9e81ac1d3/.travis.yml#L61

Please provide the AppImage file for download on GitHub Releases, thanks.

**Comment by b00f** [comment]
Currently it's inside zip file in current release. It's part of the tihu project.
`  - cd .. && tar -cvzf tihu-linux-x64.tar.gs ./build`

**Comment by probonopd** [comment]
> Currently it's inside zip file in current release. 

Please don't put an AppImage inside a zip. It defeats the purpose. Also it prevents the AppImage from passing our automated tests to be included in the AppImageHub central directory of available AppImages.

https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by b00f** [comment]
This project is not aimed to make an executable program. It includes a library to be called inside other application. The app image is just an example how to call it. I put it under zip for developers who wants to check how it works.

**Comment by probonopd** [comment]
Thanks for the explanation.

**Comment by b00f** [comment]
I should thank you for your help. I can see you are always helpful.
